version: '3.3'
services:
  nodered:
    volumes:
      - shared:/filestorage
  ftp:
    image: openlpr/ftp:1.0
    restart: always
    environment:
      PRODUCTION: production
    depends_on:
      - broker
      - mongodb
    ports:
      - 2121:2121
    volumes:
      - shared:/filestorage
  platedetector:
    image: openlpr/platedetector:1.0
    restart: always
    environment:
      PRODUCTION: production
    depends_on:
      - broker
      - mongodb
    volumes:
      - shared:/filestorage
      - ./models:/models
  plateclassifier:
      image: openlpr/plateclassifier:1.0
      restart: always
      environment:
        PRODUCTION: production
      depends_on:
        - broker
        - mongodb
      volumes:
        - shared:/filestorage
        - ./models:/models
  ocr:
      image: openlpr/ocr:1.0
      restart: always
      environment:
        PRODUCTION: production
      depends_on:
        - broker
        - mongodb
      volumes:
        - shared:/filestorage
        - ./models:/models
volumes:
  shared:
    driver: local
    driver_opts:
      type: none
      device: $PWD/filestorage
      o: bind