version: '3.1'
services:
  broker:
    image: rabbitmq:3.7.14-management
    restart: always
    ports:
      - 15672:15672
      - 5672:5672
  nodered:
    image: openlpr/nodered:v10
    restart: always
    environment:
      - PORT=1890
    ports:
      - '1890:1890'
  mongodb:
    image: mongo:4.1.11-bionic
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: lpr
      MONGO_INITDB_ROOT_PASSWORD: lpr
    ports:
      - 27017:27017